# !-----------------------------------------------------------------------------------------------!
#
#    1) To disable/hide message, set it to [] or "none".
#    2) For UNICODE CHARACTERS (smileys, symbols, ..), save the file in UTF-8 encoding.
#    3) Instead of using %% in placeholders, use {}.
#    4) You can use types in "Message" sections, see https://github.com/AdoNikeOFFICE/EpicChat/wiki/Message-Types.
#    5) Color codes are supported with '&', '§', '{#hex}' or #hex (Hex colors are only supported from 1.16+ Minecraft version).
#    >  Examples: "&cHello."; "{#756D0B}Hello". For hex colors I recommend using https://htmlcolorcodes.com/.
#    6) PlaceholderAPI and Built-in placeholders are available, see https://github.com/AdoNikeOFFICE/EpicChat/wiki/Placeholders.
#    7) You can find Sounds there: https://github.com/kangarko/Foundation/blob/master/src/main/java/org/mineacademy/fo/remain/CompSound.java,
#       some of them are not initialized yet, use the name of the Sound from the "...".
#
# !-----------------------------------------------------------------------------------------------!

# -------------------------------------------------------------------------------------------------
# This is the prefix before the messages.
# -------------------------------------------------------------------------------------------------
Prefix: "&4&lEpicChat &8// &7"

Chat:
  # -------------------------------------------------------------------------------------------------
  # Do you want to enable this feature?
  # -------------------------------------------------------------------------------------------------
  Enabled: true

  # -------------------------------------------------------------------------------------------------
  # What's the command aliases for this plugin?
  #
  # The main command is hard coded, it's "/epicchat".
  # -------------------------------------------------------------------------------------------------
  Aliases:
    - "chat"

  # -------------------------------------------------------------------------------------------------
  # What's the permission to use the chat?
  #
  # Set this to 'none' to disable it.
  # -------------------------------------------------------------------------------------------------
  Permission: "none"

  # -------------------------------------------------------------------------------------------------
  # What's the permission to use the colors in the chat?
  #
  # Set this to 'none' to disable it.
  # -------------------------------------------------------------------------------------------------
  Permission_Color: "epicchat.color"

  # -------------------------------------------------------------------------------------------------
  # Do you want to send the chat to the console?
  # -------------------------------------------------------------------------------------------------
  Log_Enabled: true

  # -------------------------------------------------------------------------------------------------
  # What's the default chat format?
  # -------------------------------------------------------------------------------------------------
  Format: "{vault_prefix} &f{player_name} &8• {message}"

  # -------------------------------------------------------------------------------------------------
  # Color used in {message} placeholder in the "Format".
  # -------------------------------------------------------------------------------------------------
  Message_Color: "&7"

  # -------------------------------------------------------------------------------------------------
  # What's the chat format for specified group?
  #
  # Example Usage:
  # Group_Format:
  #  - Name: "owner"
  #    Format: "{vault_prefix} &f{player_name} &8• {message}"
  #    Message_Color: "&c"
  #  - Name: "admin"
  #    Format: "&2Admin &7{player_name} &8> {message}"
  #    Message_Color: "&a"
  #
  # For this feature Vault and Permission plugin need to be installed.
  # -------------------------------------------------------------------------------------------------
  Group_Format: [ ]

  # -------------------------------------------------------------------------------------------------
  # What's the shown message when player hovers on the chat format?
  #
  # Set this to "Hover: []" to disable it.
  # -------------------------------------------------------------------------------------------------
  Hover:
    - "&8• &f{player_name}'s &7Profile"
    - " "
    - " &2| &7First Joined &a{player_first_join_date}"
    - " &2| &7Time Played &a{statistic_time_played:days}d {statistic_time_played:hours}h {statistic_time_played:minutes}m"
    - " "
    - " &3| &7Kills &b{statistic_player_kills} &7kill(s)"
    - " &3| &7Deaths &b{statistic_deaths} &7death(s)"
    - " "
    - " &e> Click to send a message to this player"
    - " "
    - " &8&oMessage sent on {timestamp_short}"

  # -------------------------------------------------------------------------------------------------
  # What's the suggested message, when player clicks to the chat format?
  #
  # Set this to "Hover_Click_Command: []" to disable it.
  # -------------------------------------------------------------------------------------------------
  Hover_Click_Command: "/msg {0} "

  # -------------------------------------------------------------------------------------------------
  # What's the emojis, that can be replaced in the chat?
  #
  # Set this to "Emojis: []" to disable it.
  # -------------------------------------------------------------------------------------------------
  Emoji:
    # -------------------------------------------------------------------------------------------------
    # Do you want to enable this feature?
    # -------------------------------------------------------------------------------------------------
    Enabled: true

    # -------------------------------------------------------------------------------------------------
    # What's the color of emoji in the chat message?
    # -------------------------------------------------------------------------------------------------
    Color: "&e"

    Emojis:
      - What_To_Replace: ":)"
        Replace_To: "☺"
      - What_To_Replace: "=)"
        Replace_To: "☻"
      - What_To_Replace: ":check_mark:"
        Replace_To: "☑"
      - What_To_Replace: ":x:"
        Replace_To: "⊠"
      - What_To_Replace: "o/"
        Replace_To: "(づ｡◕‿‿◕｡)づ"
      - What_To_Replace: ":heart:"
        Replace_To: "❤"
      - What_To_Replace: ":star:"
        Replace_To: "⭐"
      - What_To_Replace: ":arrow:"
        Replace_To: "➜"
      - What_To_Replace: ":java:"
        Replace_To: "☕"
      - What_To_Replace: ":table_flip:"
        Replace_To: "(╯°□°）╯︵ ┻━┻"

  Cooldown:
    # -------------------------------------------------------------------------------------------------
    # Do you want to enable this feature?
    # -------------------------------------------------------------------------------------------------
    Enabled: true

    # -------------------------------------------------------------------------------------------------
    # What's the permission, that bypasses cooldown?
    #
    # Set this to 'none' to disable it.
    # -------------------------------------------------------------------------------------------------
    Permission: "chat.cooldown.bypass"

    # -------------------------------------------------------------------------------------------------
    # What's the message when someone spams?
    #
    # Placeholders:
    # > {time} - shows time left
    # > {time_plural} - shows time left + second/seconds
    # -------------------------------------------------------------------------------------------------
    Message: "{actionbar}{prefix}You can write again in &f{time_plural}&7."

    # -------------------------------------------------------------------------------------------------
    # What's the time in seconds that player can write again?
    # -------------------------------------------------------------------------------------------------
    Delay_Seconds: 3

  Mention:
    # -------------------------------------------------------------------------------------------------
    # Do you want to enable Mention feature?
    # -------------------------------------------------------------------------------------------------
    Enabled: true

    # -------------------------------------------------------------------------------------------------
    # What's the message when player mentions someone?
    # -------------------------------------------------------------------------------------------------
    Message: "{title}&a{target_name}|&7Mentioned you!"

    # -------------------------------------------------------------------------------------------------
    # What's the color "format" of mentioned name in the chat message?
    # -------------------------------------------------------------------------------------------------
    Color: "&f@"

    # -------------------------------------------------------------------------------------------------
    # What's the sound played to the mentioned player?
    # -------------------------------------------------------------------------------------------------
    Sound: LEVEL_UP

  # -------------------------------------------------------------------------------------------------
  # You can setup own Discord bot, if you wish.
  #
  # How to do it? See https://github.com/AdoNikeOFFICE/EpicChat/wiki/Discord
  # -------------------------------------------------------------------------------------------------
  Discord:
    # -------------------------------------------------------------------------------------------------
    # Do you want to enable this feature?
    # -------------------------------------------------------------------------------------------------
    Enabled: false

    # -------------------------------------------------------------------------------------------------
    # Do you want to send the discord message send to Minecraft chat to the console?
    # -------------------------------------------------------------------------------------------------
    Log_Enabled: true

    # -------------------------------------------------------------------------------------------------
    # The Discord bot Token.
    # -------------------------------------------------------------------------------------------------
    Token: "BOT_TOKEN"

    # -------------------------------------------------------------------------------------------------
    # The Discord bot Activity.
    # -------------------------------------------------------------------------------------------------

    Test:
      # -------------------------------------------------------------------------------------------------
      # Available types:
      # - PLAYING
      # - STREAMING
      # - LISTENING
      # - WATCHING
      # - CUSTOM_STATUS
      # - COMPETING
      # -------------------------------------------------------------------------------------------------
      Type: "PLAYING"

      # -------------------------------------------------------------------------------------------------
      # Available placeholders:
      # - {online}
      # - {max}
      # - {tps}
      # - {server_name}
      # - {timestamp_short}
      # -------------------------------------------------------------------------------------------------
      Message: "play.server.net ({online}/{max})"

      # -------------------------------------------------------------------------------------------------
      # What's the repeat time to update the Activity placeholders?
      # -------------------------------------------------------------------------------------------------
      Repeat_Every: "1 minute"

    # -------------------------------------------------------------------------------------------------
    # What's the ID of the Discord channel, where chat message will be sent?
    #
    # From the Discord to the Minecraft
    # &
    # From the Minecraft to the Discord
    # -------------------------------------------------------------------------------------------------
    Chat_Channel_ID: "000000000000000000"

    # -------------------------------------------------------------------------------------------------
    # What's the message sent in the Minecraft chat?
    # -------------------------------------------------------------------------------------------------
    Chat_Format: "{chat}&9&lDiscord &8| &f{member_mention} &7wrote &f{message}"

    # -------------------------------------------------------------------------------------------------
    # What's the message sent in the Discord channel?
    # -------------------------------------------------------------------------------------------------
    Discord_Format: "Minecraft | [MOB KILLS: {statistic_mob_kills}] {player_name} wrote {message}"

  # -------------------------------------------------------------------------------------------------
  # What's the questions to ask to the players?
  # -------------------------------------------------------------------------------------------------
  Question:
    # -------------------------------------------------------------------------------------------------
    # Do you want to enable this feature?
    # -------------------------------------------------------------------------------------------------
    Enabled: true

    # -------------------------------------------------------------------------------------------------
    # What's the repeat time to send the random question?
    # -------------------------------------------------------------------------------------------------
    Repeat_Every: "10 minutes"

    # -------------------------------------------------------------------------------------------------
    # What's the time to cancel the question, when inactive?
    # -------------------------------------------------------------------------------------------------
    Inactive_Cancel: "1 minute"

    Questions:
      - Question: "{actionbar}{prefix}&7[?] &fWhat is the answer to the life, the universe and everything? &7[?]"
        Answer: "42"
      - Question: "{chat}{prefix}Multi-line message here\n<center>&7[?] &fMake up the word 'E__c' &7[?]\nHello, I am AdoNikeOFFICE."
        Answer: "Epic"
        Sound: SUCCESSFUL_HIT

    Rewards:
      - "gamemode creative {player}"
      - "give {player} diamond"

  Announcement:
    # -------------------------------------------------------------------------------------------------
    # Do you want to enable this feature?
    # -------------------------------------------------------------------------------------------------
    Enabled: true

    # -------------------------------------------------------------------------------------------------
    # What's the repeat time to send the random announcement?
    # -------------------------------------------------------------------------------------------------
    Repeat_Every: "15 minutes"

    Announcements:
      - Sound: CAT_HISS
        Permission: "none"
        Chat_Message:
          - " "
          - "<center>&b| &3ANNOUNCEMENT &b|"
          - " "
          - "<center>&7This is the example announcement"
          - "<center>&7that you can send to your players."
          - " "
      - Permission: "chat.announcement"
        Chat_Message:
          - " "
          - "<center>&e| &6ANNOUNCEMENT &e|"
          - " "
          - "<center>&7This is the example announcement"
          - "<center>&7that you can send to the players"
          - "<center>&7with the permission 'chat.announcement'."
          - " "

Command:
  Reload:
    # -------------------------------------------------------------------------------------------------
    # What's the permission to use the reload command?
    #
    # Set this to 'none' to disable it.
    # -------------------------------------------------------------------------------------------------
    Permission: "chat.command.reload"

Message:
  # -------------------------------------------------------------------------------------------------
  # What's the message, when sender is console?
  # -------------------------------------------------------------------------------------------------
  No_Console: "You need to use this command in-game."

  # -------------------------------------------------------------------------------------------------
  # What's the permission message, when player don't have specific permission?
  # -------------------------------------------------------------------------------------------------
  No_Permission: "You don't have enough permission to use this. &f({0})"

  # -------------------------------------------------------------------------------------------------
  # What's the message, when plugin sub-command doesn't exist?
  # -------------------------------------------------------------------------------------------------
  Invalid_Args: "Invalid arguments. Type &f/ec &7for help."

  # -------------------------------------------------------------------------------------------------
  # What's the message, when player is muted?
  #
  # This message supports: [Essentials, CMI, BanManager, AdvancedBan & LiteBans]
  # -------------------------------------------------------------------------------------------------
  Muted: "You can't use the chat, while you are muted."

  # -------------------------------------------------------------------------------------------------
  # What's the message, when player is muted?
  #
  # This message supports: AuthMe
  # -------------------------------------------------------------------------------------------------
  Not_Logged: "You can't use the chat, while you are not logged."

  Question_Message:
    Guessed: "&f{0} &7have guessed the answer! &f({1})"
    Inactive_Cancel: "The question was inactive. Expired, wait for the new one!"

# -------------------------------------------------------------------------------------------------
# DO NOT EDIT. Otherwise it will corrupt your plugin installation!
# -------------------------------------------------------------------------------------------------
Version: 6